version: "3.9"

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      PORT: ${SERVICE_PORT}
      DB_URL: "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
      NATS_URL: "nats://${NATS_HOST}:${NATS_PORT}"
      NATS_CLUSTER_ID: "${NATS_CLUSTER_ID}"
      ORDERS_BUF_SIZE: "${ORDERS_BUF_SIZE}"
    restart: unless-stopped
    depends_on:
      - postgres
      - nats

  postgres:
    image: postgres:${DB_TAG}
    container_name: ${DB_HOST}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./sql:/docker-entrypoint-initdb.d:ro"
    restart: unless-stopped

  nats:
    image: nats-streaming:${NATS_TAG}
    container_name: ${NATS_HOST}
    command:
      - "--cluster_id"
      - "${NATS_CLUSTER_ID}"
      - "--port"
      - "${NATS_PORT}"
      - "--http_port"
      - "${NATS_HTTP_PORT}"
    ports:
      - "${NATS_PORT}:${NATS_PORT}"
      - "${NATS_HTTP_PORT}:${NATS_HTTP_PORT}"
    volumes:
      - "nats:/data"
    restart: unless-stopped

volumes:
  postgres:
  nats:
